### ISSUE TITLE
Feature Request: Add ability to import a file

### ISSUE THREAD

**Issue by unashamedgeek** [0xceba/burp_variables#1]
My feature request is to add the ability to import an initial file.  For example, in working with an API swagger file, I may have up to 100 variables that I want to set. I can do it rather quickly with some scripting to create a csv or tsv. It would then be useful if I could import that file into this extension versus adding a row and doing each one individually. Thank you.

**Comment by 0xceba** [comment]
Thank you for the feature request. Import/export functionality has been added with commit 0795bac602726c81b6d309b9f2484cfd7d65a561.
